In [7]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [8]:
import jax
import jax.numpy as jnp
import torch
import optax


In [9]:

x_t = torch.randn(10).cuda()
m_t = torch.randn(5, 20).cuda()

x_j = jax.dlpack.from_dlpack(x_t)
m_j = jax.dlpack.from_dlpack(m_t)


In [10]:
x_t[7:300]

tensor([ 1.7310, -1.4227,  0.5018], device='cuda:0')

In [6]:
m_t[m_t > 0].shape

torch.Size([49])

In [11]:
jnp.sum(0)

Array(0, dtype=int32)

In [9]:
sum(3)

TypeError: 'int' object is not iterable

In [4]:
print(jnp.sqrt(jnp.mean(x_j**2)))
print(torch.sqrt(torch.mean(x_t**2)))

1.1223795
tensor(1.1224)


In [5]:
print(jax.nn.softmax(m_j), jax.nn.softmax(m_j).shape)
print(torch.nn.functional.softmax(m_t), torch.nn.functional.softmax(m_t).shape)

[[0.09618212 0.05916178 0.11385506 0.04406569 0.0134258  0.02512521
  0.07545603 0.04197667 0.00796455 0.02775626 0.03632289 0.01237059
  0.0069953  0.06285039 0.15638438 0.04885745 0.01784063 0.10412237
  0.02922109 0.02006571]
 [0.02237038 0.12036026 0.15185152 0.01995911 0.0020597  0.06189092
  0.0269219  0.14377189 0.04723367 0.06027987 0.00725451 0.01243648
  0.01254815 0.03610086 0.03335752 0.02815148 0.01307184 0.02181175
  0.05490839 0.12365981]
 [0.1339422  0.024477   0.00455591 0.04273033 0.00204361 0.01373508
  0.08140083 0.05766259 0.01686894 0.0189508  0.06690101 0.01912696
  0.04780746 0.06078091 0.01031403 0.13625614 0.03994136 0.10154942
  0.10385837 0.01709702]
 [0.01664236 0.01912084 0.16201779 0.1958671  0.12122416 0.0315703
  0.01135486 0.02081415 0.01048253 0.03808502 0.064602   0.01683129
  0.04551661 0.01593884 0.03036786 0.01366975 0.01599243 0.02226397
  0.14021344 0.0074247 ]
 [0.0989776  0.02065883 0.07779507 0.00580626 0.04011901 0.28009307
  0.04921303 0.02

/tmp/ipykernel_2477333/2331782141.py:2: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  print(torch.nn.functional.softmax(m_t), torch.nn.functional.softmax(m_t).shape)


In [6]:
print(jnp.concatenate(list(m_j), axis=0), jnp.concatenate(list(m_j), axis=0).shape)
print(torch.cat(list(m_t), dim=0), torch.cat(list(m_t), dim=0).shape)

[ 1.2307962   0.7448285   1.399479    0.4502343  -0.738269   -0.1115755
  0.9881029   0.40166688 -1.2604473  -0.01198584  0.25700086 -0.82012564
 -1.3902084   0.80530995  1.7168697   0.5534595  -0.45396855  1.3101196
  0.03944339 -0.33643502 -0.17440483  1.508347    1.7407608  -0.28845635
 -2.5595796   0.8432311   0.01079767  1.6860855   0.57296455  0.8168558
 -1.3005195  -0.7615087  -0.75256944  0.3041742   0.22514082  0.05545757
 -0.71168226 -0.19969349  0.72352386  1.5353919   1.115256   -0.5844185
 -2.2657268  -0.02724335 -3.067434   -1.1621993   0.6172331   0.27245623
 -0.9566787  -0.84030616  0.42106158 -0.8310534   0.08502939  0.32512328
 -1.4486474   1.1323841  -0.09474019  0.8383931   0.8608758  -0.9432481
 -0.79755265 -0.65872484  1.4782022   1.6679324   1.1881374  -0.1572871
 -1.1798577  -0.5738708  -1.259794    0.03031707  0.55874133 -0.78626436
  0.20857322 -0.8407454  -0.19611928 -0.9943184  -0.83738875 -0.5065345
  1.3336619  -1.6046915   1.4425156  -0.1242352   1.201700

In [7]:
x_j.shape

(10,)

In [8]:
optax.kl_divergence(m_j, m_j**2)

Array([-3.3394163, 21.757278 , 73.084274 ,  6.2489467, 13.063147 ],      dtype=float32)

In [9]:
torch.nn.functional.kl_div(m_t, m_t**2, reduction="none").sum(dim=-1).mean()

tensor(22.1628)

In [12]:
torch.nn.functional.kl_div(m_t, m_t**2, reduction="batchmean")

tensor(22.1628)

In [15]:
torch.pi

3.141592653589793

In [16]:
import numpy as np
import scipy as sp

In [17]:
sp.special.gammaln(1.5)

np.float64(-0.12078223763524526)

In [21]:
torch.log(torch.tensor(torch.pi))

tensor(1.1447)

In [22]:
np.log(np.pi)

np.float64(1.1447298858494002)

In [28]:
# on GPU
x = jnp.array([-1, 0, 1])
print(x.device)

cuda:0


In [29]:
jnp.log(sp.special.erfc(jnp.array([-1, 0, 1]))).device

CudaDevice(id=0)

In [35]:
torch.log(torch.special.erfcx(torch.tensor([-1, 2, 1], device="cuda")))

tensor([ 1.6112, -1.3649, -0.8496], device='cuda:0')

In [37]:
torch.where(x_t < 0, 1, torch.log(torch.special.erfcx(x_t)) - x_t**2)

tensor([ 1.0000,  1.0000, -0.2652,  1.0000, -5.8456, -1.5607, -0.8628, -0.9190,
        -2.5656,  1.0000])

In [44]:
x_t.cuda() / np.sqrt(2)

tensor([-1.3205, -0.1476,  0.1481, -0.2243,  1.4895,  0.6268,  0.4015,  0.4218,
         0.8846, -0.8532], device='cuda:0')

In [45]:
torch.sqrt(3.)

TypeError: sqrt(): argument 'input' (position 1) must be Tensor, not float

In [49]:
abs(torch.tensor(1., device="cuda"))

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [50]:
torch.stack([torch.tensor(1., device="cuda"), torch.tensor(2., device="cuda")])

tensor([1., 2.], device='cuda:0')

In [56]:
all(x_t.cuda() > 0)

False

In [64]:
abs(x_t.cuda())

tensor([1.8675, 0.2087, 0.2095, 0.3172, 2.1064, 0.8864, 0.5678, 0.5965, 1.2510,
        1.2066], device='cuda:0')

In [57]:
torch.logsumexp

<function torch._VariableFunctionsClass.logsumexp>

In [58]:
torch.minimum(x_t, x_t**2)

tensor([-1.8675, -0.2087,  0.0439, -0.3172,  2.1064,  0.7858,  0.3224,  0.3558,
         1.2510, -1.2066])

In [59]:
jnp.minimum(x_j, x_j**2)

Array([-1.8674781 , -0.20868118,  0.04387966, -0.31723955,  2.106423  ,
        0.7857765 ,  0.32240006,  0.35580242,  1.2509658 , -1.2066083 ],      dtype=float32)

In [65]:
torch.clip(x_t.cuda(), torch.zeros_like(x_t.cuda()), x_t.cuda()**2)

tensor([0.0000, 0.0000, 0.0439, 0.0000, 2.1064, 0.7858, 0.3224, 0.3558, 1.2510,
        0.0000], device='cuda:0')

In [66]:
torch.clip(x_t.cuda(), torch.zeros_like(x_t.cuda()), None)

tensor([0.0000, 0.0000, 0.2095, 0.0000, 2.1064, 0.8864, 0.5678, 0.5965, 1.2510,
        0.0000], device='cuda:0')

In [69]:
H_j = jnp.array([[1., 3.], [3., 4.]])
H_t = torch.tensor([[1., 3.], [3., 4.]], device="cuda")

In [71]:
evals, evecs = jnp.linalg.eigh(H_j)
print(evals)
print(evecs)
evals, evecs = torch.linalg.eigh(H_t)
print(evals)
print(evecs)


[-0.854102   5.8541026]
[[ 0.85065085  0.52573115]
 [-0.52573115  0.85065085]]
tensor([-0.8541,  5.8541], device='cuda:0')
tensor([[ 0.8507,  0.5257],
        [-0.5257,  0.8507]], device='cuda:0')


In [72]:
jnp.linalg.norm(x_j)

Array(3.5492759, dtype=float32)

In [73]:
torch.norm(x_t.cuda())

tensor(3.5493, device='cuda:0')

In [75]:
torch.outer(x_t.cuda(), x_t.cuda()).shape

torch.Size([10, 10])

In [78]:
torch.linalg.svdvals(m_t.cuda())

tensor([5.6466, 5.1045, 4.7594, 4.1404, 3.0992], device='cuda:0')

In [81]:
np.linspace(np.log10(3), np.log10(10), 10)

array([0.47712125, 0.53521889, 0.59331653, 0.65141417, 0.70951181,
       0.76760945, 0.82570708, 0.88380472, 0.94190236, 1.        ])

In [85]:
np.concatenate([np.linspace(np.log10(3), np.log10(10), 10), np.linspace(np.log10(1000), np.log10(3), 10)]).astype(int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 3, 2, 2, 2, 1, 1, 1, 1, 0, 0])

In [87]:
torch.inf * torch.ones(10, device="cuda")

tensor([inf, inf, inf, inf, inf, inf, inf, inf, inf, inf], device='cuda:0')

In [94]:
z = torch.stack([torch.sum(x_t.cuda())]*3)

In [96]:
z[2] += 1

In [109]:
x_t[:, None].shape

torch.Size([10, 1])

In [117]:
torch.stack([x_t.cuda(), x_t.cuda()], dim=-1)

tensor([[-1.8675, -1.8675],
        [-0.2087, -0.2087],
        [ 0.2095,  0.2095],
        [-0.3172, -0.3172],
        [ 2.1064,  2.1064],
        [ 0.8864,  0.8864],
        [ 0.5678,  0.5678],
        [ 0.5965,  0.5965],
        [ 1.2510,  1.2510],
        [-1.2066, -1.2066]], device='cuda:0')

In [110]:


def unit(v, **kwargs):
    return v / torch.norm(v, **kwargs)


In [115]:
unit(m_t.cuda(), dim=1, keepdim=True).norm(dim=1)

tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000], device='cuda:0')

In [107]:
torch.manual_seed(42)
print(torch.randn(10, 2))
print(torch.randn(10, 2))

tensor([[ 1.9269,  1.4873],
        [ 0.9007, -2.1055],
        [-0.7581,  1.0783],
        [ 0.8008,  1.6806],
        [ 0.3559, -0.6866],
        [-0.4934,  0.2415],
        [-0.2316,  0.0418],
        [-0.2516,  0.8599],
        [-0.3097, -0.3957],
        [ 0.8034, -0.6216]])
tensor([[ 0.3189, -0.4245],
        [ 0.3057, -0.7746],
        [-0.8371, -0.9224],
        [ 1.8113,  0.1606],
        [ 0.3672,  0.1754],
        [ 1.3852, -0.4459],
        [-1.2024,  0.7078],
        [-1.0759,  0.5357],
        [ 1.1754,  0.5612],
        [-0.4527, -0.7718]])


In [136]:
torch.logsumexp(torch.tensor([1_000_000., 999_999.99]), dim=-1)

tensor(1000000.6875)

In [137]:
jax.scipy.special.logsumexp(jnp.array([1_000_000., 999_999.99]), axis=-1)

Array(1000000.7, dtype=float32)

In [139]:
from typing import Tuple, Union

def weighted_logsumexp(
    logx: torch.Tensor,
    w: torch.Tensor,
    dim: int,
    keepdim: bool = False,
    return_sign: bool = False,
) -> Union[torch.Tensor, Tuple[torch.Tensor, torch.Tensor]]:
    """
    from https://github.com/PhilippDahlinger/torch_weighted_logsumexp
    
    This is a Pytorch port of the Tensorflow function `reduce_weighted_logsumexp` from
    https://www.tensorflow.org/probability/api_docs/python/tfp/math/reduce_weighted_logsumexp
    Computes log(abs(sum(weight * exp(elements across tensor dimensions)))) in a numerically stable way.
    Right now, it only supports to perform the operation over 1 dimension. (mandatory parameter)
    :param logx: Tensor to reduce
    :param w: weights, has to be same shape as logx
    :param dim: dimension to reduce
    :param keep_dim: if True, retains reduced dimensions with length 1
    :param return_sign: if True, return the sign of weight * exp(elements across tensor dimensions)))
    :return: Either the reduced tensor or a tuple of the reduced tensor and the sign
    """
    log_absw_x = logx + torch.log(torch.abs(w))
    max_log_absw_x = torch.amax(log_absw_x, dim=dim, keepdim=True)
    max_log_absw_x = torch.where(
        torch.isinf(max_log_absw_x),
        torch.zeros(torch.Size([]), dtype=max_log_absw_x.dtype, device=max_log_absw_x.device),
        max_log_absw_x)
    wx_over_absw_x = torch.sign(w) * torch.exp(log_absw_x - max_log_absw_x)
    sum_wx_over_max_absw_x = torch.sum(wx_over_absw_x, dim=dim, keepdim=keepdim)
    if not keepdim:
        max_log_absw_x = torch.squeeze(max_log_absw_x, dim=dim)
    sgn = torch.sign(sum_wx_over_max_absw_x)
    lswe = max_log_absw_x + torch.log(sgn * sum_wx_over_max_absw_x)
    if return_sign:
        return lswe, sgn
    else:
        return lswe

In [176]:
rr_t = torch.randn(10, 2).cuda()
rr_j = jax.dlpack.from_dlpack(rr_t)

In [178]:
weighted_logsumexp(rr_t, 
                   torch.tensor([1., -1.], device="cuda"), dim=-1)

tensor([ 0.7189,  0.8785, -0.0223, -1.1490, -0.0799,  0.0048, -0.9557, -0.5013,
         1.1053, -0.3878], device='cuda:0')

In [186]:
weighted_logsumexp(rr_t, w=torch.ones_like(rr_t)/2, dim=-1)

tensor([ 0.9764,  0.6442, -0.1470,  0.0365, -0.1549,  0.0823,  0.5257,  0.0992,
         0.6928,  0.6979], device='cuda:0')

In [147]:
1+np.log(1-1/np.exp(1))

np.float64(0.5413248546129181)

In [169]:
jax.random.normal(key=jax.random.PRNGKey(42), shape=(10, 2))

Array([[-0.02830462,  0.46713185],
       [ 0.29570296,  0.15354592],
       [-0.12403282,  0.21692315],
       [-1.4408789 ,  0.7558599 ],
       [ 0.52140963,  0.9101704 ],
       [-0.3844966 ,  1.1398233 ],
       [ 1.4457862 ,  1.0809066 ],
       [-0.05629321,  0.9095945 ],
       [ 0.55734617,  0.21905719],
       [-1.4485087 ,  0.7641875 ]], dtype=float32)

In [185]:
jax.scipy.special.logsumexp(rr_j,
                      b=1/2,
                      axis=-1)

Array([ 0.97643006,  0.6441725 , -0.14702275,  0.036503  , -0.154903  ,
        0.08230504,  0.525661  ,  0.09921877,  0.6927911 ,  0.6979144 ],      dtype=float32)

In [189]:
np.pi - torch.pi

0.0

In [187]:
torch.sinc(x_t.cuda())

tensor([-0.0689,  0.9299,  0.9294,  0.8425,  0.0496,  0.1254,  0.5479,  0.5093,
        -0.1805, -0.1595], device='cuda:0')

In [191]:
np.sinc(x_j)

array([-0.06893069,  0.92989045,  0.9293678 ,  0.8424823 ,  0.04958704,
        0.12540717,  0.54792935,  0.50930524, -0.18046935, -0.15945804],
      dtype=float32)

In [190]:
jnp.sinc(x_j)

Array([-0.06893069,  0.92989045,  0.9293678 ,  0.8424823 ,  0.04958703,
        0.12540717,  0.54792935,  0.50930524, -0.18046935, -0.15945804],      dtype=float32)

In [194]:
assert max(x_t.cuda()) > 3

AssertionError: 